[package]
name = "freetds-sys"
version = "0.1.0"
edition = "2021"
links = "freetds"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.60.1"
make-cmd = "0.1"
num_cpus = "1.13"
